### ISSUE TITLE
File limit is doesn't work. Possible to add any count of files. 

### ISSUE THREAD

**Issue by dmytrodemchenko** [pIvan/file-upload#14]

**Comment by pIvan** [comment]
Hi @dmytrodemchenko,

The file limitation is validator not the physical restriction,
you can add an unlimited number of files, but that's why you have
error object, it is same as any other angular form component error.

You don't restricting user to bring as many files he want, 
insead you can rise him a message with file limitation note.

**Comment by dmytrodemchenko** [comment]
Hi @pIvan,
Thanks a lot for your response! 

We can close this one. 
Thanks a lot for your helping.

**Comment by pIvan** [comment]
also if you want to count how many file is uploaded, you can use
value.length with FormControl instance and method size with FileUploadControl instance

**Comment by dmytrodemchenko** [comment]
@pIvan could you please help #15?
