### ISSUE TITLE
Export FileUploadIconComponent in FileUploadModule

### ISSUE THREAD

**Issue by julienboulay** [pIvan/file-upload#27]
Hi,

I would like to create my own custom file-upload-list-item to be able to localize the "remove" button and style the file list.
Could you please add FileUploadIconComponent to the exports section, so that I can reuse the icon ?
Thanks

**Comment by julienboulay** [comment]
It could be nice also to have FileUploadService exported from public_api to be able to import it in another ts file.

**Comment by pIvan** [comment]
Hi @julienboulay I'll do both things.

**Comment by pIvan** [comment]
> Hi,
> 
> I would like to create my own custom file-upload-list-item to be able to localize the "remove" button and style the file list.
> Could you please add FileUploadIconComponent to the exports section, so that I can reuse the icon ?
> Thanks

FileUploadService will be exposed through public API but FileUploadIconComponent could be
a problem, because some projects may already use the same selector as FileUploadIconComponent (file-upload-icon).
The idea with this file upload component is to be an abstraction on which anybody can build his design.
I will consider about naming convention and if programmers repeatedly
reports the need for child components, I'll work on exposing it through public API.

**Comment by pIvan** [comment]
to use FileUploadService register it in @Component or @Module as provider
