### ISSUE TITLE
help, does not validate or update the .valid or .invalid

### ISSUE THREAD

**Issue by jict3493** [pIvan/file-upload#43]
Hi, I'm doing a dynamic form and the validations don't work for me. I've tried everything, I've even read all the closed issues, I'd appreciate your help.

At the moment this a little hardcoded, the idea is to take fields from a database and with those fields create a form.

this is the modal-participar.page.ts
![code4](https://user-images.githubusercontent.com/4748708/84165228-745bf080-aa41-11ea-8709-3e064e36cba2.png)

this the HTML
![code2](https://user-images.githubusercontent.com/4748708/84090372-96149380-a9bf-11ea-932a-0535a8fea642.png)

this is the module
![code3](https://user-images.githubusercontent.com/4748708/84090421-be03f700-a9bf-11ea-9dc5-8001c65f5de4.png)

and a few screenshots
![image](https://user-images.githubusercontent.com/4748708/84090492-fd324800-a9bf-11ea-8e34-f437324c0cc2.png)

![image](https://user-images.githubusercontent.com/4748708/84090538-1e933400-a9c0-11ea-816d-b6da56f1c361.png)

**Comment by pIvan** [comment]
Hi @jict3493 thank You for detailed explanation!

**Comment by pIvan** [comment]
Hi @jict3493, I just saw how you use FileUploadControl with angular reactive form, that would not work, FileUploadControl is used only when you want to use fileupload as stand alone component, otherwise use FormControl or ngModel to connect it with Angular forms.
In this particular case use FormControl (for **accept** use element attribute or you can combine it FileUploadControl instance).

Kind regards.
