### ISSUE TITLE
Duplicated file entries in multiple mode

### ISSUE THREAD

**Issue by notbear** [pIvan/file-upload#60]
Hello
I found some inconsistency while selecting files.

**Observed**:
In single mode if I choose another file the previous is replaced.
But in multiple mode new files are just added to the list as new entries even if they existed on the list. 

**Expected**
The list of files should not contain duplicates if the same file is added more than once. 

<hr>

Duplicated entries:
<img src="https://user-images.githubusercontent.com/1796050/122836563-be351300-d2f2-11eb-920d-9a37913c32a7.gif" width="500" >

Native control behavior:
<img src="https://user-images.githubusercontent.com/1796050/122836686-fdfbfa80-d2f2-11eb-83a4-ea5f5b9d711b.gif" width="500" >

**Comment by pIvan** [comment]
Hi @notbear, thanks! I'll try to fix this in next few days.

**Comment by pIvan** [comment]
Hi @notbear,

the possibility of uploading more files is intentionally left so that it is possible to continue adding files several times, they can be deleted if the `discard` option is enabled, then depending on the validators they will be removed from the list.

With `native` parameter it should act as a native input field,
and each time when new files are added, the previous should be deleted.

example how to enable it:
`new FileUploadControl({ native: true })`

example 2:
`<file-upload native="true"></file-upload>`

**Comment by notbear** [comment]
Hello. Thanks for a quick update! There must have been some misunderstanding between us. I was perfectly fine with adding files multiple times. It's a good UX. 
My only concern was about duplicated entries. If the same file was chosen again it appeared twice on the list.

**Comment by pIvan** [comment]
> Hello. Thanks for a quick update! There must have been some misunderstanding between us. I was perfectly fine with adding files multiple times. It's a good UX.
> My only concern was about duplicated entries. If the same file was chosen again it appeared twice on the list.

Oh I see, 
will be corrected ;)

**Comment by pIvan** [comment]
Corrected with version 3.3.1.
Kind regards.
