### ISSUE TITLE
MaxSizeLimit for the total size when multiple file selection is supported

### ISSUE THREAD

**Issue by Dineshrajaa** [pIvan/file-upload#62]
Hi @pIvan ,

Is there anyway we can restrict file uploads beyond a size limit say 5 MB when we are supporting multiple file upload?

PS: File size limit should be checked against total file size of the selected files not individual items.

**Comment by pIvan** [comment]
To preserve the simple logic behind the component, the validators are the same as they were,
what I did is, add a new validator `sizeLimit` which checks the summary size of all the files submitted to the component.
There may be cases where the user can upload 5 files, but each can have a limit of 5MB, that's why I did not changed the current logic.
