### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by matthewtquinn1** [pIvan/file-upload#67]
Hi, it's me again! 

Are you planning on updating this repository to support Angular 13?

Thank you :)

**Comment by pIvan** [comment]
Hi @matthewtquinn1,

latest version is angular 13 supported, is there any issue with it?

**Comment by matthewtquinn1** [comment]
Oh perfect, I didn't realise - sorry! And thanks for the quick response!

**Comment by jerone** [comment]
Came here with the same question, because neither the [readme](https://github.com/pIvan/file-upload#readme), nor the [releases](https://github.com/pIvan/file-upload/releases), nor the [changelog](https://github.com/pIvan/file-upload/blob/master/CHANGELOG.md) mention any support for Angular 13.

Thank you for confirming.
