### ISSUE TITLE
File upload validators for .pdf

### ISSUE THREAD

**Issue by paulociva** [pIvan/file-upload#9]
I'm trying to apply a pdf file filter, but it does not display error if I select other file types.

See here: https://stackblitz.com/edit/angular-file-upload-test

**Comment by pIvan** [comment]
Hi @paulociva,

component is marked as invalid, you can check class atribute on
component (**ng-invalid**)

`<file-upload formcontrolname="files" class="ng-tns-c1-0 has-files ng-touched ng-dirty ng-invalid list-visible" ng-reflect-name="files"></file-upload>`

this way you can check error objects
`this.demoForm.controls.file.errors` or `this.filesControl.errors`

also if you check formGroup status you can see how it is invalid
`this.demoForm.status`

in accordance with this you can make error displaying

**Comment by paulociva** [comment]
Hi @pIvan,

Thanks for the reply, but I could not simulate the display of the error messages, you can look at the same example as before.

And one more question, can I "reject" the file that is not the one I select?

**Comment by pIvan** [comment]
use `this.demoForm.controls.files.errors` instead `this.demoForm.controls.file.errors`
it prepares the same object like any other angular validator, depending on the error object
you can prepare message, also you can change drop zone template to suit you're needs.

Component does not have the ability to reject something what user add because it is not user friendly
action, I will consider to add that functionality in next version

**Comment by pIvan** [comment]
I'm closing this because validators are working correct
